## YAML Template.
---
spring:
    profiles: dev
    datasource:
        username: root
        password: Orcl.12345
#        password: root
        url: jdbc:mysql://localhost:3306/REPORT
    
    # To prevent the batch job to start automatically.
    # All configured jobs are run automatically by
    # Spring Boot's auto configuration service
    batch:
        job:
            enabled: false

app:
    chunkSize: 12000
    maxThread: 10
    delimeter: "|"
    insertAccessLogQuery: 
        INSERT INTO access_log (log_date, ip_address, request, status, user_agent) 
        VALUES (:logDate, :ipAddress, :request, :status, :userAgent)
    findBlockedIpAddressesQuery: 
        select a.ip_address from 
            (select ip_address, count(0) log_count 
            from access_log 
            where log_date 
                between STR_TO_DATE(:start_date, '%Y-%m-%d.%H:%i:%s') 
                and STR_TO_DATE(:end_date, '%Y-%m-%d.%H:%i:%s') 
            group by ip_address) a 
        where log_count > :threshold
    insertBlockedIpQuery: 
        INSERT INTO blocked_ip (ip_address, reason) 
        VALUES (:ipAddress, :reason)
    accessLogColumnNames:
        - logDate
        - ipAddress
        - request
        - status
        - userAgent
    threshold:
        hourly: 200
        daily: 500
    duration:
        hourly: 1
        daily: 24
    datePattern: yyyy-MM-dd.HH:mm:ss
    
logging:
    level: 
        ch.qos.logback: ERROR
        
