## YAML Template.
---
spring:
    profiles: dev
    datasource:
        username: CIBUTUATADM
        password: CIBUTUATADM
        url: jdbc:oracle:thin:@bdoulxu209.bdo.com.ph:1521:CIBUTUAT
        driver-class: oracle.jdbc.driver.OracleDriver
#        username: root
#        password: Orcl.12345
#        url: jdbc:mysql://localhost:3306/CIBUTUATADM
    
    # To prevent the batch job to start automatically.
    # All configured jobs are run automatically by
    # Spring Boot's auto configuration service
    batch:
        job:
            enabled: false

app:
    chunkSize: 20000
    delimeter: "|"
    insertAccessLogQuery: INSERT INTO access_log (log_date, ip_address, request, status, user_agent) VALUES (:logDate, :ipAddress, :request, :status, :userAgent)
    accessLogColumnNames:
        - logDate
        - ipAddress
        - request
        - status
        - userAgent
    threshold:
        hourly: 200
        daily: 500
